### ISSUE TITLE
BUG E PEDIDO DE ALTERAÇÃO

### ISSUE THREAD

**Issue by BigBossPT** [KewaiiGamer/Kewaii-VIPMenu#1]
Boa noite, gostaria de reportar o bug em que os players estao sempre a dar !vipmenu na mesma ronda e selecionam tudo.

Sugestoes a adicionar: 
- VIPSPAWN alternativo (0 ou 1)
- Adicionar um X de Vida quando VIP mata alguem.

**Comment by KewaiiGamer** [comment]
Em primeiro lugar não consigo repodruzir o bug de que tu tanto reclamas. Tu não o testastes porque eu acabei de o fazer e está a funcionar perfeitamente

Depois tu devias ter feito 2 issues. Um para o bug e outra para as sugestões.

Em relação às tais sugestões eu irei implementá-las na próxima versão ;)
